FROM python:3.10-bullseye

WORKDIR /api
ADD ./requirements.txt ./

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && python3 -m pip install --upgrade setuptools \
    && pip install -r requirements.txt

CMD python manage.py migrate; python manage.py runserver 0.0.0.0:8000; 
    