version: '3.8'

services:
  nginx:
    container_name: proxy
    image: "nginx:mainline-alpine"
    volumes:
      - ./nginx/conf.d/default.conf.test:/etc/nginx/conf.d/default.conf
    ports:
      - "80:2000"
    depends_on:
      - api
      - app
  
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.test
    volumes:
      - ./app:/app
    env_file:
      - ./.env/app.test.env
    environment:
      - PORT=80
      - NODE_ENV=development
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.test
    volumes:
      - ./api:/api
    env_file:
      - ./.env/api.test.env
      - ./.env/db.test.env
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
    depends_on:
      - redis
      - db
  
  redis:
    container_name: redis
    image: redis:6.2-bullseye
  
  db:
    container_name: db
    image: postgres:14.1-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env/db.test.env
  
volumes:
  postgres_data: